### PR TITLE
fix issue with server request

### PR DESCRIPTION
**Pull request by koloja**

### CODE REVIEW

**Comment by supercrafter100** [comment]
Did you test this? I doubt this would actually fix it seeing as you are pushing null as the link to select a server

**Comment by koloja** [comment]
ive tested it locally
you dont need the `|| null` part tho
im pretty sure its just the `?` you need

**Comment by supercrafter100** [comment]
Did the ability to select servers still function? This really sounds like its going to break something down the line

**Comment by koloja** [comment]
it didnt function at all
it would just crash after you login

**Comment by supercrafter100** [comment]
No as in does selecting actually work now 😅

**Comment by koloja** [comment]
if you mean can i actually select a server now
yes

**Comment by koloja** [comment]
i would also like to say that i get the error `cheerio does not provide a default export`
an easy fix

**Comment by supercrafter100** [comment]
I made a proper fix in 90f25d0 but thank you for the effort!

**Pull request closed without merging**
